### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by addod19**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
Hi there @addod19 
You did a great job cloning this page 👍. But the purpose of this project was creating a grayscale using HTML containers to represents parts of the page and then highlight the most important parts of it using shades of gray. Before merging to master we need to do some changes to be in line with Microverse guidelines. They are:

- [ ] The navbar should have seven separate containers to represent the 7 links (<div> is recommended)

- [ ] It seems that your navbar has one of its container on top of the logo's container.

- [ ] All content should be wrapped with main HTML tags

- [ ] Every child of main should be a section HTML tag pair

- [ ] Every child of section should be an article HTML tag pair

Please, kindly make these changes and submit for code review again.

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @addod19
You have done a great job working all alone, please can you tell me why you're working on a collaborative project all alone ?
***It will be great to have live version link inside README file***
I can see you made all the changes from previous review, You are almost through with the project in fact your :+1: awaits you.....
All you have to do now is fix the validations errors, see a screenshot from your web page below;
image
image

_Hint:_ It is advisable to use `class` instead of `id` for multiple styling.
Tips:
For every HTML/CSS projects please check your files with the W3 Validator [here](https://validator.w3.org/) and the CSS Linter
_Check out this [video tutorial](https://www.loom.com/share/f7688bd6dbb54ae2a4e80a621fa7665d), if you need help checking for error validations_

Please, kindly make these changes and submit for code review again.

**Comment by addod19** [comment]
I am working on this project alone because my coding partner has suspended the program....

**Review by bellom — COMMENTED** [review]
Hi @addod19 
## Congratulation 👍, you have really done a great job correcting all the errors!
_Go ahead and merge to master and don't forget to submit project completion form._
You should get a new coding partner after the HTML section, kindly be patient.

**Pull request merged**
